"""Report assembly: GSTR-1 6A export + document bundle (design §15)."""
import base64
import csv
import io
import zipfile

from fastapi import APIRouter, Depends, Response
from app.middleware.auth import require_internal_token
from app.models.schemas import GstrExportRequest, GeneratedDoc, BundleRequest
from app.services.gstr_export import build_gstr_6a
from app.services.pdf_generator import render_invoice_pdf
from app.utils.storage import save_bytes

router = APIRouter(prefix="/generate", tags=["reports"], dependencies=[Depends(require_internal_token)])


@router.post("/gstr", response_model=GeneratedDoc)
async def generate_gstr(req: GstrExportRequest) -> GeneratedDoc:
    xlsx = build_gstr_6a(req.invoices)
    key = f"reports/gstr6a-{req.orgId}-{req.financialYear}.xlsx"
    url = save_bytes(key, xlsx, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
    return GeneratedDoc(url=url, storageKey=key)


def _safe(name: str) -> str:
    return "".join(c if c.isalnum() or c in "-._ " else "_" for c in str(name)).strip() or "file"


@router.post("/bundle")
async def generate_bundle(req: BundleRequest) -> Response:
    """Zip every invoice PDF + FIRC files + a manifest + LUT reference for a financial year."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        # 1) Invoice PDFs
        for inv in req.invoices:
            number = _safe(inv.get("number", "invoice")).replace("/", "-")
            try:
                pdf = render_invoice_pdf(inv)
                z.writestr(f"invoices/{number}.pdf", pdf)
            except Exception as e:  # noqa: BLE001 — keep building the rest of the bundle
                z.writestr(f"invoices/_ERROR-{number}.txt", f"Could not render PDF: {e}")

        # 2) FIRC / e-FIRA files
        for f in req.firc:
            try:
                data = base64.b64decode(f.base64)
                z.writestr(f"firc/{_safe(f.invoiceNumber).replace('/', '-')}-{_safe(f.filename)}", data)
            except Exception:  # noqa: BLE001
                pass

        # 3) Manifest CSV
        man = io.StringIO()
        w = csv.writer(man)
        w.writerow(["Number", "Type", "Date", "Currency", "Taxable value", "Tax total",
                    "Grand total", "INR equivalent", "Status", "FEMA due"])
        for inv in req.invoices:
            w.writerow([inv.get("number"), inv.get("type"), inv.get("invoiceDate"), inv.get("currency"),
                        inv.get("subtotal"), inv.get("taxTotal"), inv.get("grandTotal"),
                        inv.get("inrEquivalent"), inv.get("status"), inv.get("femaDueDate") or ""])
        z.writestr("manifest.csv", man.getvalue())

        # 4) LUT reference
        s = req.seller or {}
        lut = (
            "LUT (Letter of Undertaking) reference\n"
            "=====================================\n"
            f"Legal name : {s.get('legalName') or 'N/A'}\n"
            f"GSTIN      : {s.get('gstin') or 'N/A'}\n"
            f"LUT number : {s.get('lutNumber') or 'N/A'}\n"
            f"LUT FY     : {s.get('lutFy') or 'N/A'}\n"
            f"LUT ARN    : {s.get('lutArn') or 'N/A'}\n"
            f"Bank A/C   : {s.get('bankAccount') or 'N/A'}\n"
            f"Bank IFSC  : {s.get('bankIfsc') or 'N/A'}\n"
        )
        z.writestr("LUT-reference.txt", lut)

        # 5) README
        z.writestr(
            "README.txt",
            f"Crossbill document bundle — FY {req.financialYear}\n"
            f"{len(req.invoices)} invoice(s), {len(req.firc)} FIRC file(s).\n\n"
            "Contents:\n"
            "  invoices/       — PDF of every invoice for the year\n"
            "  firc/           — bank remittance proofs (FIRC / e-FIRA)\n"
            "  manifest.csv    — a summary of all invoices\n"
            "  LUT-reference.txt — your LUT & bank details\n\n"
            "Generated by Crossbill · Built by Anujali Technologies. Review with your CA before filing.\n",
        )

    buf.seek(0)
    filename = f"crossbill-bundle-{_safe(req.financialYear)}.zip"
    return Response(
        content=buf.getvalue(),
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
